# This is a Docker Compose configuration for local use.
# In production use docker-compose.prod.yaml

# Run all services:
# docker compose up --build --detach

services:
  api:
    build: . # See Dockerfile for more details
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8004:8000"
    volumes:
      - "./settings.yaml:/code/settings.yaml:ro" # Read-only settings file
    env_file: .env # You can specify some Uvicorn settings in .env file
    environment:
      - TZ=Europe/Moscow # Set the timezone for correct calendar image generation

  db:
    # See more: https://registry.hub.docker.com/_/mongo
    image: "mongo:7.0"
    restart: always
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"
    env_file: .env # Set username and password in .env file
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/db --quiet
      start_period: 10s
      start_interval: 1s
      interval: 1m
      timeout: 5s
      retries: 3

  minio:
    # See more: https://registry.hub.docker.com/minio/minio
    image: "minio/minio:RELEASE.2024-05-10T01-41-38Z"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio:/data"
    command: server /data --console-address ":9001"
    env_file: .env # Set username and password in .env file

volumes:
  mongodb:
  minio:
