# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
api_settings:
  db_url: "mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin"
minio:
  access_key: "minioadmin"
  secret_key: "password"
ml_service:
  api_key: "secret_token"
  mongo_url: "mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin"
  openrouter_api_key: "your openrouter api key"
  system_prompt: "You are a helpful assistant. Write the answer in the same language as the question."
  timeout: 10.0
