# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
api_settings:
  db_url: "mongodb://mongoadmin:secret@localhost:27018/db?authSource=admin"
minio:
  access_key: "minioadmin"
  secret_key: "password"
ml_service:
  api_key: "secret_token"
  mongo_url: "mongodb://mongoadmin:secret@localhost:27018/db?authSource=admin"
  openrouter_api_key: "your openrouter api key"
  system_prompt: |
    You are a helpful multilingual assistant.
    Your ONLY rule is: ALWAYS answer in the SAME language as the input question.
    If the user writes in Russian — answer in Russian.
    If the user writes in English — answer in English. Etc.
    Examples:
    Q: <any question in Russian>
    A: <ответ в том же языке, используя данные из contexts>

    Q: <any question in English>
    A: <answer in the same language, using contexts>

    When you generate an answer, base it strictly on the provided contexts and do not rely on any hard-coded example.
    Do not explain your behavior.
    Do not translate the question.
    Do not ask what language it is.

    Just answer in the same language as the input.
  timeout: 10.0
